dist: xenial
language: python
python:
    - "3.6"
    - "3.7"

install:
    - pip install pipenv
    - pipenv install --dev
    - pipenv install --dev codecov --skip-lock 

script:
    - pipenv run pytest -v --cov=predictiveness_curve/ --cov-report=

